# RGB TO HSV PADA PEPAYA 1

DIMAS PRATIKTO
06.2018.1.06958

In [1]:
import cv2
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsRegressor

In [2]:
original = cv2. imread('pepaya 1.jpeg')

In [3]:
#Resize Gambar
h, w = original.shape[:2]
new_h, new_w= int(h/2), int(w/2)
image= cv2.resize(original,(new_w, new_h))

In [4]:
#Convert RGB KE HSV
hsv= cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

In [5]:
#Print Nilai HSV
print(hsv)

[[[160   8  91]
  [160   9  83]
  [160   9  83]
  ...
  [120  17  88]
  [120  18  84]
  [120  20  75]]

 [[160  10  79]
  [160   9  82]
  [160   8  92]
  ...
  [120  16  98]
  [120  16  95]
  [120  18  85]]

 [[160   9  81]
  [160  10  80]
  [160   8  95]
  ...
  [120  14 107]
  [120  15 104]
  [120  16  93]]

 ...

 [[ 17  10 172]
  [ 17  10 179]
  [ 17  10 173]
  ...
  [128   6 158]
  [128   6 158]
  [128   6 163]]

 [[ 17  10 173]
  [ 17  10 181]
  [ 17  10 174]
  ...
  [128   6 160]
  [128   6 164]
  [128   6 172]]

 [[ 17  10 171]
  [ 17  10 174]
  [ 17  10 176]
  ...
  [128   6 157]
  [128   7 153]
  [128   7 154]]]


In [6]:
#Menampilkan Gambar HSV
cv2.imshow('Gambar HSV', hsv)

In [7]:
#Menampilkan Gambar Tiap H,S,V
cv2.imshow('H Channel', hsv[: ,: ,0])
cv2.imshow('S Channel', hsv[: ,: ,1])
cv2.imshow('V Channel', hsv[: ,: ,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Memperoleh Nilai Rata-Rata Tiap H,S,V
H = hsv[: ,: ,0]
S = hsv[: ,: ,1]
V = hsv[: ,: ,2]
meanH = np.mean(H)
meanH = float(meanH)
meanS = np.mean(S)
meanS = float(meanS)
meanV = np.mean(V)
meanV = float(meanV)
print("Nilai Rata-rata H :", meanH,"S: ", meanS,"V: ",meanV)

Nilai Rata-rata H : 113.95255729166666 S:  26.726208333333332 V:  127.92390104166667


# PENERAPAN KNN PADA DATASET DAN NILAI RATA-RATA

In [9]:
#Dataset Csv 
data=pd.read_csv('datapepaya.csv')

In [10]:
#Memasukkan Dataset Kedalam X & Y
X = data[['Hmean','Smean','Vmean']]
Y = data['Kematangan']
#Prediksi Menggunakan KNN
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X,Y)
dataa = [meanH,meanS,meanV]
hasilprediksi = knn.predict([dataa])
hasilprediksi = float(hasilprediksi)
print("Hasil Prediksi =",hasilprediksi)
#Hasil prediksi
#Bila Hasil Prediksi Bernilai == 1(Pepaya Matang) & Bernilai == 0 (Pepaya Mentah)
if hasilprediksi == 1:
    print("Pepaya ini Matang")
elif hasilprediksi == 0:
    print("Pepaya ini Mentah")
else:
    print("Kematangan Tidak Di Prediksi")

Hasil Prediksi = 0.0
Pepaya ini Mentah
