# RGB TO HSV PADA PEPAYA 3

DIMAS PRATIKTO
06.2018.1.06958

In [1]:
import cv2
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsRegressor

In [2]:
original = cv2. imread('pepaya 3.jpeg')

In [3]:
#Resize Gambar
h, w = original.shape[:2]
new_h, new_w= int(h/2), int(w/2)
image= cv2.resize(original,(new_w, new_h))

In [4]:
#Convert RGB KE HSV
hsv= cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

In [5]:
#Print Nilai HSV
print(hsv)

[[[ 10   7 106]
  [ 10   7 108]
  [ 10   7 107]
  ...
  [128  15  70]
  [128  14  72]
  [128  12  85]]

 [[ 10   8 100]
  [ 10   7 103]
  [ 10   7 104]
  ...
  [128  13  76]
  [128  12  83]
  [128  11  91]]

 [[ 10   8  96]
  [ 10   8  99]
  [ 10   8 100]
  ...
  [128  13  81]
  [128  11  89]
  [128  11  93]]

 ...

 [[  0   0 141]
  [  0   0 143]
  [  0   0 147]
  ...
  [100   7 111]
  [100   7 106]
  [100   8 102]]

 [[  0   0 143]
  [  0   0 142]
  [  0   0 146]
  ...
  [100   7 106]
  [100   7 104]
  [100   8 102]]

 [[  0   0 140]
  [  0   0 145]
  [  0   0 148]
  ...
  [100   7 103]
  [100   8 101]
  [100   7 103]]]


In [6]:
#Menampilkan Gambar HSV
cv2.imshow('Gambar HSV', hsv)

In [7]:
#Menampilkan Gambar Tiap H,S,V
cv2.imshow('H Channel', hsv[: ,: ,0])
cv2.imshow('S Channel', hsv[: ,: ,1])
cv2.imshow('V Channel', hsv[: ,: ,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Memperoleh Nilai Rata-Rata Tiap H,S,V
H = hsv[: ,: ,0]
S = hsv[: ,: ,1]
V = hsv[: ,: ,2]
meanH = np.mean(H)
meanH = float(meanH)
meanS = np.mean(S)
meanS = float(meanS)
meanV = np.mean(V)
meanV = float(meanV)
print("Nilai Rata-rata H :", meanH,"S: ", meanS,"V: ",meanV)

Nilai Rata-rata H : 100.477546875 S:  30.234489583333332 V:  130.562078125


# PENERAPAN KNN PADA DATASET DAN NILAI RATA-RATA

In [9]:
#Dataset Csv 
data=pd.read_csv('datapepaya.csv')

In [10]:
#Memasukkan Dataset Kedalam X & Y
X = data[['Hmean','Smean','Vmean']]
Y = data['Kematangan']
#Prediksi Menggunakan KNN
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X,Y)
dataa = [meanH,meanS,meanV]
hasilprediksi = knn.predict([dataa])
hasilprediksi = float(hasilprediksi)
print("Hasil Prediksi =",hasilprediksi)
#Hasil prediksi
#Bila Hasil Prediksi Bernilai == 1(Pepaya Matang) & Bernilai == 0 (Pepaya Mentah)
if hasilprediksi == 1:
    print("Pepaya ini Matang")
elif hasilprediksi == 0:
    print("Pepaya ini Mentah")
else:
    print("Kematangan Tidak Di Prediksi")

Hasil Prediksi = 0.0
Pepaya ini Mentah
