# RGB TO HSV PADA PEPAYA 4

DIMAS PRATIKTO
06.2018.1.06958

In [1]:
import cv2
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsRegressor

In [2]:
original = cv2. imread('pepaya 4.jpeg')

In [3]:
#Resize Gambar
h, w = original.shape[:2]
new_h, new_w= int(h/2), int(w/2)
image= cv2.resize(original,(new_w, new_h))

In [4]:
#Convert RGB KE HSV
hsv= cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

In [5]:
#Print Nilai HSV
print(hsv)

[[[ 11  20 100]
  [ 11  22  94]
  [ 11  23  90]
  ...
  [  6  16  78]
  [  6  16  82]
  [  6  14  88]]

 [[ 11  22  92]
  [ 11  23  87]
  [ 11  24  84]
  ...
  [  6  20  65]
  [  6  21  61]
  [  6  17  77]]

 [[ 17  21  87]
  [ 17  21  84]
  [ 17  21  84]
  ...
  [  6  15  86]
  [  6  17  74]
  [  6  16  78]]

 ...

 [[ 17  12 144]
  [ 17  13 135]
  [ 17  14 129]
  ...
  [135   3 147]
  [135   4 138]
  [135   4 135]]

 [[ 17  13 140]
  [ 17  13 139]
  [ 17  13 139]
  ...
  [135   3 146]
  [135   4 141]
  [135   4 142]]

 [[ 17  13 140]
  [ 17  12 143]
  [ 17  12 146]
  ...
  [135   4 144]
  [135   4 138]
  [135   4 139]]]


In [6]:
#Menampilkan Gambar HSV
cv2.imshow('Gambar HSV', hsv)

In [7]:
#Menampilkan Gambar Tiap H,S,V
cv2.imshow('H Channel', hsv[: ,: ,0])
cv2.imshow('S Channel', hsv[: ,: ,1])
cv2.imshow('V Channel', hsv[: ,: ,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Memperoleh Nilai Rata-Rata Tiap H,S,V
H = hsv[: ,: ,0]
S = hsv[: ,: ,1]
V = hsv[: ,: ,2]
meanH = np.mean(H)
meanH = float(meanH)
meanS = np.mean(S)
meanS = float(meanS)
meanV = np.mean(V)
meanV = float(meanV)
print("Nilai Rata-rata H :", meanH,"S: ", meanS,"V: ",meanV)

Nilai Rata-rata H : 65.78804382093317 S:  55.213043820933166 V:  126.16011191677175


# PENERAPAN KNN PADA DATASET DAN NILAI RATA-RATA

In [9]:
#Dataset Csv 
data=pd.read_csv('datapepaya.csv')

In [10]:
#Memasukkan Dataset Kedalam X & Y
X = data[['Hmean','Smean','Vmean']]
Y = data['Kematangan']
#Prediksi Menggunakan KNN
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X,Y)
dataa = [meanH,meanS,meanV]
hasilprediksi = knn.predict([dataa])
hasilprediksi = float(hasilprediksi)
print("Hasil Prediksi =",hasilprediksi)
#Hasil prediksi
#Bila Hasil Prediksi Bernilai == 1(Pepaya Matang) & Bernilai == 0 (Pepaya Mentah)
if hasilprediksi == 1:
    print("Pepaya ini Matang")
elif hasilprediksi == 0:
    print("Pepaya ini Mentah")
else:
    print("Kematangan Tidak Di Prediksi")

Hasil Prediksi = 0.3333333333333333
Kematangan Tidak Di Prediksi
