# RGB TO HSV PADA PEPAYA 5

DIMAS PRATIKTO
06.2018.1.06958

In [11]:
import cv2
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsRegressor

In [12]:
original = cv2. imread('pepaya 5.jpg')

In [13]:
#Resize Gambar
h, w = original.shape[:2]
new_h, new_w= int(h/2), int(w/2)
image= cv2.resize(original,(new_w, new_h))

In [14]:
#Convert RGB KE HSV
hsv= cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

In [15]:
#Print Nilai HSV
print(hsv)

[[[160   8  93]
  [160   8  90]
  [160   9  86]
  ...
  [175  15 105]
  [175  15 105]
  [175  15 105]]

 [[160   8  91]
  [160   9  89]
  [160   9  87]
  ...
  [175  15 104]
  [175  15 104]
  [175  15 104]]

 [[160   9  89]
  [160   9  89]
  [160   9  89]
  ...
  [174  13 101]
  [174  13 101]
  [174  13 101]]

 ...

 [[109  89  23]
  [109  93  22]
  [109  97  21]
  ...
  [130 109  14]
  [140 102  15]
  [140 102  15]]

 [[109  85  24]
  [109  89  23]
  [109  89  23]
  ...
  [130  96  16]
  [140 102  15]
  [140 109  14]]

 [[109  85  24]
  [109  85  24]
  [109  89  23]
  ...
  [130  96  16]
  [140  96  16]
  [140 102  15]]]


In [16]:
#Menampilkan Gambar HSV
cv2.imshow('Gambar HSV', hsv)

In [17]:
#Menampilkan Gambar Tiap H,S,V
cv2.imshow('H Channel', hsv[: ,: ,0])
cv2.imshow('S Channel', hsv[: ,: ,1])
cv2.imshow('V Channel', hsv[: ,: ,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
#Memperoleh Nilai Rata-Rata Tiap H,S,V
H = hsv[: ,: ,0]
S = hsv[: ,: ,1]
V = hsv[: ,: ,2]
meanH = np.mean(H)
meanH = float(meanH)
meanS = np.mean(S)
meanS = float(meanS)
meanV = np.mean(V)
meanV = float(meanV)
print("Nilai Rata-rata H :", meanH,"S: ", meanS,"V: ",meanV)

Nilai Rata-rata H : 107.64719403931515 S:  207.56261889663918 V:  147.19863665187063


# PENERAPAN KNN PADA DATASET DAN NILAI RATA-RATA

In [19]:
#Dataset Csv 
data=pd.read_csv('datapepaya.csv')

In [20]:
#Memasukkan Dataset Kedalam X & Y
X = data[['Hmean','Smean','Vmean']]
Y = data['Kematangan']
#Prediksi Menggunakan KNN
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X,Y)
dataa = [meanH,meanS,meanV]
hasilprediksi = knn.predict([dataa])
hasilprediksi = float(hasilprediksi)
print("Hasil Prediksi =",hasilprediksi)
#Hasil prediksi
#Bila Hasil Prediksi Bernilai == 1(Pepaya Matang) & Bernilai == 0 (Pepaya Mentah)
if hasilprediksi == 1:
    print("Pepaya ini Matang")
elif hasilprediksi == 0:
    print("Pepaya ini Mentah")
else:
    print("Kematangan Tidak Di Prediksi")

Hasil Prediksi = 1.0
Pepaya ini Matang
