# RGB TO HSV PADA PEPAYA 6

DIMAS PRATIKTO
06.2018.1.06958

In [1]:
import cv2
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsRegressor

In [2]:
original = cv2. imread('pepaya 6.jpg')

In [3]:
#Resize Gambar
h, w = original.shape[:2]
new_h, new_w= int(h/2), int(w/2)
image= cv2.resize(original,(new_w, new_h))

In [4]:
#Convert RGB KE HSV
hsv= cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

In [5]:
#Print Nilai HSV
print(hsv)

[[[ 25 121 120]
  [ 25 122 121]
  [ 25 129 121]
  ...
  [ 28  30 143]
  [ 60   7 145]
  [ 94  12 143]]

 [[ 25 122 119]
  [ 25 118 123]
  [ 24 122 123]
  ...
  [ 33  15 150]
  [ 68   7 148]
  [ 79  14 145]]

 [[ 25 119 122]
  [ 25 119 122]
  [ 23 121 122]
  ...
  [ 80   5 145]
  [ 84   9 141]
  [ 69  12 147]]

 ...

 [[ 31  56 160]
  [ 33  60 158]
  [ 34  70 146]
  ...
  [ 50  14 160]
  [ 86  13 157]
  [ 93  19 158]]

 [[ 28  60 156]
  [ 30  60 152]
  [ 30  64 147]
  ...
  [ 73  20 155]
  [ 88  20 156]
  [ 96  23 156]]

 [[ 28  64 147]
  [ 30  65 141]
  [ 31  67 145]
  ...
  [ 76  18 158]
  [ 87  18 157]
  [ 96  25 156]]]


In [6]:
#Menampilkan Gambar HSV
cv2.imshow('Gambar HSV', hsv)

In [7]:
#Menampilkan Gambar Tiap H,S,V
cv2.imshow('H Channel', hsv[: ,: ,0])
cv2.imshow('S Channel', hsv[: ,: ,1])
cv2.imshow('V Channel', hsv[: ,: ,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Memperoleh Nilai Rata-Rata Tiap H,S,V
H = hsv[: ,: ,0]
S = hsv[: ,: ,1]
V = hsv[: ,: ,2]
meanH = np.mean(H)
meanH = float(meanH)
meanS = np.mean(S)
meanS = float(meanS)
meanV = np.mean(V)
meanV = float(meanV)
print("Nilai Rata-rata H :", meanH,"S: ", meanS,"V: ",meanV)

Nilai Rata-rata H : 89.28606666666667 S:  162.51493333333335 V:  165.20206666666667


# PENERAPAN KNN PADA DATASET DAN NILAI RATA-RATA

In [9]:
#Dataset Csv 
data=pd.read_csv('datapepaya.csv')

In [10]:
#Memasukkan Dataset Kedalam X & Y
X = data[['Hmean','Smean','Vmean']]
Y = data['Kematangan']
#Prediksi Menggunakan KNN
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X,Y)
dataa = [meanH,meanS,meanV]
hasilprediksi = knn.predict([dataa])
hasilprediksi = float(hasilprediksi)
print("Hasil Prediksi =",hasilprediksi)
#Hasil prediksi
#Bila Hasil Prediksi Bernilai == 1(Pepaya Matang) & Bernilai == 0 (Pepaya Mentah)
if hasilprediksi == 1:
    print("Pepaya ini Matang")
elif hasilprediksi == 0:
    print("Pepaya ini Mentah")
else:
    print("Kematangan Tidak Di Prediksi")

Hasil Prediksi = 1.0
Pepaya ini Matang
